server:
  port: 8100
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://host:port/****
    username: ****
    password: ****
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp